# Задание 1
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [1]:
import pandas as pd

In [36]:
#Используемый датасет: MovieLens Latest Datasets   ml-latest-small.zip

my_movies = pd.read_table('movies.csv', sep=',', header=0)
my_ratings = pd.read_table('ratings.csv', sep=',', header=0)
movies_merge = pd.merge(my_movies, my_ratings, on='movieId', how='left')

In [79]:
#Первый вариант - за счёт мерджа, каждая строка для фильма - это отдельная оценка. Считаем value_counts()
movies_merge[movies_merge['rating'] == 5 ]['title'].value_counts().head(1)

Shawshank Redemption, The (1994)    153
Name: title, dtype: int64

In [103]:
#Второй вариант - группировка и список по убыванию
movies_grp = movies_merge[movies_merge['rating'] == 5 ].groupby('title').count()['rating'].sort_values(ascending=False)
movies_grp = pd.DataFrame(movies_grp)
movies_grp.columns = ['rating > 5 (count)']
movies_grp.head()

                                           rating > 5 (count)
title
Shawshank Redemption, The (1994)                          153
Pulp Fiction (1994)                                       123
Forrest Gump (1994)                                       116
Matrix, The (1999)                                        109
Star Wars: Episode IV - A New Hope (1977)                 104

# Задание 2
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [132]:
#Загрузка данных и проверка названия стран
power = pd.read_csv('power.csv')
power['country'].unique()

array(['Austria', 'Belgium', 'Czechia', 'Finland', 'France', 'Greece',
       'Hungary', 'Italy', 'Korea, Republic of', 'Netherlands', 'Romania',
       'Serbia', 'Slovakia', 'Ukraine', 'United Kingdom', 'United States',
       'Brunei Darussalam', 'Bulgaria', 'Canada', 'Chile', 'Croatia',
       'Iran (Islamic Rep. of)', 'Jordan', 'Lithuania', 'Mexico', 'Oman',
       'Other Asia', 'Poland', 'Portugal', 'Spain', 'Sweden',
       'Switzerland', 'T.F.Yug.Rep. Macedonia', 'Turkey', 'Uzbekistan',
       'Argentina', 'Colombia', 'Germany', 'Norway', 'Australia',
       'China, Macao SAR', 'Japan', 'Denmark', 'Ireland', 'Philippines',
       'Bangladesh', 'Eritrea', 'Ethiopia', 'Lesotho', 'Nepal', 'Niger',
       'Pakistan', 'Serbia and Montenegro', 'Tunisia', 'Botswana',
       'Georgia', 'Republic of Moldova', 'Peru', 'South Africa',
       'Iceland', 'Latvia', 'Luxembourg', 'Cuba', 'Kyrgyzstan',
       'Singapore', 'Thailand', 'United Arab Emirates', 'Uruguay',
       'Armenia', 'Fiji', "Korea, Dem.Ppl's.Rep.", 'Russian Federation',
       'Swaziland', 'Zimbabwe', 'Afghanistan', 'Antigua and Barbuda',
       'Azerbaijan', 'Bahamas', 'Belize', 'Bolivia (Plur. State of)',
       'Brazil', 'Burkina Faso', 'Cameroon', 'Cayman Islands',
       'Central African Rep.', 'China', 'Comoros', 'Congo', 'Costa Rica',
       "Côte d'Ivoire", 'Dem. Rep. of the Congo', 'Dominican Republic',
       'Ecuador', 'Egypt', 'El Salvador', 'Estonia',
       'Ethiopia, incl. Eritrea', 'Faeroe Islands', 'French Guiana',
       'Germany, Fed. R. (former)', 'Greenland', 'Guatemala', 'Guinea',
       'Guyana', 'Honduras', 'Indonesia', 'Israel', 'Jamaica', 'Jersey',
       'Kazakhstan', 'Kenya', 'Kuwait', "Lao People's Dem. Rep.",
       'Liberia', 'Libya', 'Malawi', 'Malaysia', 'Maldives', 'Mauritania',
       'Mayotte', 'Morocco', 'Myanmar', 'Namibia', 'New Caledonia',
       'New Zealand', 'Nicaragua', 'Niue', 'Panama', 'Papua New Guinea',
       'Paraguay', 'Sao Tome and Principe', 'Senegal', 'Seychelles',
       'Slovenia', 'Solomon Islands', 'Sri Lanka', 'Sudan (former)',
       'Suriname', 'Togo', 'Tonga', 'Trinidad and Tobago',
       'United Rep. of Tanzania', 'Venezuela (Bolivar. Rep.)',
       'Yugoslavia, SFR (former)', 'Zambia', 'Algeria', 'Curaçao',
       'Gabon', 'Malta', 'Neth. Antilles (former)', 'Sierra Leone',
       'USSR (former)', 'Barbados', 'Benin', 'Chad', 'Djibouti',
       'French Polynesia', 'Ghana', 'Grenada', 'Guadeloupe', 'Haiti',
       'Iraq', 'Kiribati', 'Madagascar', 'Mali', 'Martinique',
       'Pacific Islands (former)', 'Palau', 'St. Helena and Depend.',
       'St. Vincent-Grenadines', 'Syrian Arab Republic', 'Uganda',
       'Yemen', 'Yemen, Dem. (former)', 'Burundi', 'India', 'Mauritius',
       'Mozambique', 'Nigeria', 'Réunion', 'Rwanda', 'Samoa', 'Somalia',
       'St. Kitts-Nevis', 'Viet Nam', 'Belarus', 'Cyprus', 'Cabo Verde',
       'Albania', 'Bahrain', 'Bosnia and Herzegovina',
       'China, Hong Kong SAR', 'Czechoslovakia (former)', 'Angola',
       'Bermuda', 'Bhutan', 'Equatorial Guinea', 'Lebanon',
       'Saudi Arabia', 'St. Lucia', 'St. Pierre-Miquelon',
       'State of Palestine', 'Tajikistan', 'German Dem. R. (former)',
       'Anguilla', 'Mongolia', 'Montenegro', 'Cambodia', 'South Sudan',
       'Sudan', 'Andorra', 'Aruba', 'Bonaire, St Eustatius, Saba',
       'British Virgin Islands', 'Dominica', 'Falkland Is. (Malvinas)',
       'Gambia', 'Gibraltar', 'Qatar', 'Sint Maarten (Dutch part)',
       'Turkmenistan', 'Turks and Caicos Islands', 'Vanuatu',
       'Guinea-Bissau', 'Micronesia (Fed. States of)', 'Timor-Leste',
       'Yemen Arab Rep. (former)', 'American Samoa', 'Liechtenstein',
       'Puerto Rico', 'Cook Islands', 'Guam', 'Guernsey', 'Isle of Man',
       'Marshall Islands', 'Montserrat', 'Nauru',
       'Northern Mariana Islands', 'Tuvalu', 'United States Virgin Is.',
       'Wallis and Futuna Is.',
       'Commonwealth of Independent States (CIS)', 'Antarctic Fisheries'],
      dtype=object)

In [139]:
#Фильтрация данных
cat = [4, 12, 21]
power = power[ power['category'].isin(cat) ] # фильтр по категориям

cnt = ['Lithuania' , 'Latvia', 'Estonia']
power = power[ power['country'].isin(cnt)] #фильтр по странам

power = power[ (power['year']>=2005) & (power['year']<=2010) ] # фильтр по годам

power = power[ power['quantity'] > 0 ] # откидываем отрицательные значения

In [185]:
#Первый вариант - суммарное потребление по всем странам одним числом
power['quantity'].sum()

240580.0

In [218]:
#Второй вариант - а-ля сводная таблица с общим итогом
import numpy as np
power_pivot = power[ ['country', 'quantity' ] ]
power_pivot = power_pivot.pivot_table(power_pivot, columns=['country'], aggfunc=np.sum)
power_pivot['total'] = power_pivot.iloc[0,:].sum()
power_pivot

country   Estonia   Latvia  Lithuania     total
quantity  63440.0  54844.0   122296.0  240580.0

# Задание 3
Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas dataframe.
Примеры страниц (необязательно брать именно эти): 
https://fortrader.org/quotes
https://www.finanz.ru/valyuty/v-realnom-vremeni

In [227]:
my_site = pd.read_html('https://www.finanz.ru/valyuty/v-realnom-vremeni', encoding='utf-8', header=0)

In [228]:
my_site[1]

,Unnamed: 0,Рубль,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
0,NaN,GBP/RUB,812096,-,806116,"0,74 %",05979,22:27:00
1,NaN,EUR/RUB,741503,-,737765,"0,51 %",03738,22:25:00
2,NaN,USD/RUB,668995,-,663195,"0,87 %",05800,22:27:00
3,NaN,JPY/RUB,06274,-,06237,"0,59 %",00037,22:27:00
4,NaN,CNY/RUB,94883,-,94165,"0,76 %",00718,22:26:00
5,NaN,CHF/RUB,681674,-,678024,"0,54 %",03650,22:27:00
6,NaN,Евро,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
7,NaN,EUR/USD,11083,-,11096,"-0,12 %",-00014,22:26:00
8,NaN,EUR/GBP,09131,-,09131,"0,00 %",00000,22:26:00
9,NaN,EUR/JPY,1181800,-,1179850,"0,17 %",01950,22:26:00
10,NaN,EUR/CHF,10876,-,10854,"0,20 %",00022,22:26:00
11,NaN,Доллар США,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
12,NaN,USD/EUR,09023,-,09012,"0,12 %",00011,22:26:00
13,NaN,USD/GBP,08239,-,08227,"0,14 %",00012,22:26:00
14,NaN,USD/JPY,1066360,-,1063350,"0,28 %",03010,22:27:00
15,NaN,USD/CHF,09814,-,09781,"0,33 %",00033,22:26:00
16,NaN,Японская иена,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
17,NaN,JPY/EUR (100:1),08500,-,08500,"-0,17 %",00000,22:27:00
18,NaN,JPY/GBP,00077,-,00077,"-0,15 %",00000,22:27:00
19,NaN,JPY/USD,00094,-,00094,"-0,28 %",00000,22:27:00
20,NaN,JPY/CHF (100:1),09200,-,09200,"0,18 %",00000,22:26:00
21,NaN,Фунт стерлингов,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
22,NaN,GBP/USD,12138,-,12151,"-0,11 %",-00014,22:26:00
23,NaN,GBP/JPY,1294454,-,1292503,"0,15 %",01952,22:27:00
24,NaN,GBP/EUR,10952,-,10956,"-0,04 %",-00004,22:26:00
25,NaN,GBP/CHF,11911,-,11870,"0,35 %",00041,22:26:00
26,NaN,Швейцарский франк,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
27,NaN,GBP/CHF,11911,-,11870,"0,35 %",00041,22:26:00
28,NaN,EUR/CHF,10876,-,10854,"0,20 %",00022,22:26:00
29,NaN,JPY/CHF (100:1),09200,-,09200,"0,18 %",00000,22:26:00
30,NaN,USD/CHF,09814,-,09781,"0,33 %",00033,22:26:00
31,NaN,Украинская гривна,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
32,NaN,EUR/UAH,279978,-,280307,"-0,12 %",-00330,22:26:00
33,NaN,USD/UAH,252630,-,252630,"0,00 %",00001,22:25:00
34,NaN,CHF/UAH,257419,-,258279,"-0,33 %",-00861,22:26:00
35,NaN,GBP/UAH,306668,-,307077,"-0,13 %",-00409,22:27:00